version: "3.5"
services:
  app:
    container_name: appTopics
    image: apptopics
    command: bash -c 'python manage.py makemigrations topics & python manage.py migrate & python manage.py runserver 0.0.0.0:8080'
    restart: always
    build: .
    ports:
      - "8080:8080"
    tty: true
networks:
  default:
    external:
      name: mongodb
