version: "3.5"
services:
  app:
    container_name: appTopics
    image: apptopics
    restart: always
    build: .
    ports:
      - "8080:8080"
    tty: true
networks:
  default:
    external:
      name: mongodb